main_win_param = {
             # 'size':'',
             # 'element_padding':'',
             # 'margins':'',
             # 'auto_close':'',
             # 'auto_close_duration':'',
             # 'icon':'',
             # 'force_toplevel':'',
             # 'return_keyboard_events':'',
             # 'use_default_focus':'',
             # 'text_justification':'',
             # 'no_titlebar':'',
             'grab_anywhere': True,
             # 'grab_anywhere_using_control':'',
             # 'keep_on_top':'',
             'resizable': True,
             # 'disable_close':'',
             # 'disable_minimize':'',
             # 'right_click_menu':'',
             # 'debugger_enabled':'',
             'finalize': True,
             # 'element_justification':'',
             # 'modal':'',
             # 'scaling':'',
             # 'sbar_width':'',
             # 'sbar_arrow_width':'',
}