import PySimpleGUI as sg

main_ico = b'iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAFBhaW50Lk5FVCA1LjEuMTGKCBbOAAAAuGVYSWZJSSoACAAAAAUAGgEFAAEAAABKAAAAGwEFAAEAAABSAAAAKAEDAAEAAAADAAAAMQECABEAAABaAAAAaYcEAAEAAABsAAAAAAAAAKOTAADoAwAAo5MAAOgDAABQYWludC5ORVQgNS4xLjExAAADAACQBwAEAAAAMDIzMAGgAwABAAAAAQAAAAWgBAABAAAAlgAAAAAAAAACAAEAAgAEAAAAUjk4AAIABwAEAAAAMDEwMAAAAADY5TB4zfSjcAAAIWRJREFUeF7tnQm0JUV9xucFVEQFVBQFRhFEBwRENpdoNEbFxIEYjXqMuMXoMYmKGyAReDxRkE1RMUZDxIBHUdwSR4l4xH0FRBZlEQaQXUadQRCJy8v33ao7aR536a7bXf+q6u93znequt+beff1u/3df/37X1XLhBBCCCGEEEIIIYQQQgghhBBCCNFXFpdt9gFoX2jOnxJCiPSAST0dWvT6HvQ0/yUhhEgHmNMc9H1vVlWdBT3Bf5sQQtgDU/rrikmN0ipoV//tZmicKkTPgRH9CZofQTsPToxnETodmp9btvaSwZnI8IUKIfrNC6BpZkUY4DwfuggmdzL0sMHZiCjCEqLHwHQ2RPMTaPvBiWb8L3QS9HZEXDcMznSMIiwh+s3LoBCzIneH/gm6AsZ3DLT54GyHKMISoqfAYDZCcyn0kMGJ2bkFOgE6HhEX+62jCEuI/vIqqC2zIptAh0GrYYYHQhsPzraIIiwhegjM5F5oroC2GJzoBua1joQ+hIiL+a6ZUYQlRD95HdSlWZEHQ++DLoNBvhxign8mFGEJ0TNgHJuhYXR1v8GJeDBfNg+djojrj4MzDVGEJUT/eBMU26zII6HToB/CNPcZnGmIIiwhegSM4gFoVkP3Hpyw47uIshrPUVSEJUS/OBiyNityiG8boQhLiJ6A6GorND+F7jk4YcdZiK7+wvcboQhLiP5wKGRtVuStvm2MIiwhegCiq+3QXAzdbXDCjs8jutrX9xujCEuIfsByAmuz4vI0jPKCkWEJUTiIrnZE83fuyJRPIro63/eDkGEJUT5HQBu4rhm/hxjlzYQMS4iCQXS1O5q/cUemnILoipXuM6GkuxAFA8M6A80z3ZEZnPj8CBjW1e4wHEVYQhQKzOpJaKzNinywDbMiirCEKBQY1tfR/Jk7MuM30MNhWK0soawIS4gCgVntjcbarMiJbZkVUYQlRGHArHhf/wDaY3DCjnXQtjCsX7rD2VGEJUR5PBuyNivyrjbNiijCEqIgEF0xCGFx5k6DE3asgbaDYbW6GYUiLCHK4oWQtVmRo9s2K6IIS4hCQHTFuYLcFPXhgxN2XA/xyeDt7rA9FGEJUQ4vh6zNinAn6NbNiijCEqIAEF1xU1Quzrf14IQdV0IrYFitbOu1FEVYQpTBqyFrsyILXZkVUYQlROYguuIa7dy264GDE3ZwgcCdYVh/cIftowhLiPzhpqjWZkXmuzQroghLiIxBdMVNUZk3YmvJedDuMCyuKtoZirCEyJsDIGuzIod0bVZEEZYQmYLoisNA5q6s9xn8DszqT32/UxRhCZEvqWyKGrxtV1MUYQmRIYiulqNh3dU9Bifs+DKiq2f4fucowhIiT7jVu7VZkaAt50NRhCVEZiC64vQbzhm03mfwvxBdcSmbaCjCEiI/DoeszeqP0EybooYgwxIiIxBdcekYLiFjzScQXV3o+9GQYQmRF2+DrO/bVjZFDUGGJYLBp/09KX8oOgbXek80UXNGY/gIois+oYyOku4iGNxA+6E5BboGuhy6DOIbeajVeGN3NnO/b+B6fwlNtBKCMdwBcVPUn7nDuMiwRDC4gZj8nTQ04ERYvrGXGhl1Fd70HFqIGuBac8su7jNozXvxd9vf96MjwxLB4Cb6GJrQBPDvIE7aXWpkNLdrcFPwKZTw4Fp/E80T3ZEZt0HcWOImdxgfGZYIBjfR2Wi62E6Kww4OMYfDzOpw83rcMJ1Psk0JXOe/RPNFd2TKUbj2/+L7JsiwRDC4kdai2dQdRYNbn78Iuhm6BTdQ9EfrMcE15j16DrTb4IQd/Fszump1n8Gm6CmhCAI3ElcKiG1WZGPoXdC3oKjTQox4DmRtVqT1TVFDUIQlgoBhcTkRmoYlfAK5HDfSz91hWeAab4DmAmjHwQk7GM1yy/lb3aEdirBEKNv71pK7Qy9z3SLh0NfarMg7UzArIsMSoaRgWOSVPs9TFPidOFfQpJp8CddBH3Bde2RYIpRUDIsrFzzVdYviFdC2rmvKEYiuOtkUNQQZlgjlEb5NgVf5tggQXXG6UwoPFFZDH3bdNJBhicb4IVgKW6IPeTZeUwrbXLXFP0Jbua4phyO6YoFvMsiwRAhbQvdy3SQoJvkO4+Ua7W9xR6ZwgUDOZEgKGZYIIZX8VZVSku9vgB7guqYciuiq001RQ5BhiRBSNKzsk+8w3PuheaM7MuVc6LOumxYyLBFCioZFck++p7IpKqOrJOdryrBECKkaVrbJd7zuLdC8zh2Z8k2Y1Rm+nxwyLBFCqoaVc/KdqyBwnqQ1Sc/P1FxC0QhEAvyQ47pIGw1OpAeXouGKmNksQYNr+hA0XD7Hep/BM3Hd9vb9JFGEJZrCHYdTNSuSY/L9MMjarGjw0bacD0WGJZqS6nCwSjbJd0RXvJ4vdUemfA7RFdfdShoZlmhKDoaVU/J9AdrQdc3gctSM8pJHhiWaktIcwnFkkXyHqe6C5gXuyJSPI7q6yPeTRoYlmpLSHMJJ5FD5fgRkfQ9yriB3P8oCGZZoSg4RFkk6+Q4zfSyafd2RKScjuuKT1SyQYYna4CZjruVh7igLUk6+M7qyhrsTpfA6aiPDEk3YBuJKmLmQZPIdr+nP0TzdHZnyAURX1/p+FsiwRBNyeEJYJdXk+9t9awnXaD/KdfNBhiWakJthkaSS73gtz0LzBHdkCrecz263IRmWaEKOhpVM8h1mxfsthZwRN0U91nXzQoYlmpCjYZFUku/PhR7juqYci+iKppUdmvwsaoMIgZsS5PSUcIj5hqu4dtwUldvq7zA4YQevAbecT2KfwaYowhK1wA3HyblcVSBHUki+7wdZmxU5KlezIoqwRC1gWCvQXOyOssRs2RlcOxrmJZB1dHoNxGvwW3eYH4qwRF1yqXAfh2Xy/R+gFIbSb8/ZrIgMS9QllzmEk4iefEd0xU1RU1hnihHmya6bLzIsUZfcIyxiUfn+Goj7OFqT3KaoIciwRF1yLWmoEjX5DnPcBM2B7sgULh3zcdfNGxmWqEsJhkViVr6/HtrcdU05DNEVF+nLHj0lFFPxeRhuPFHK++VpuIG/4vudgGt2fzSsW2OUZcnZ0GPx+2azKcckFGGJOjDhXtKHW4zkO4eC1mZFDinFrIgMS9ShlOHgkE6T7/i/H4yGyXZrvgGzOtP3i0CGJepQmmF1nXzXpqgdIcMSdSjNsEgnyXf8nw9Fk8Jk6zMQXX3T94tBhiXqUKJhdVX5Pg8xgrOEOatDXbcsZFiiDiUUjY6i1UgI0dUj0bzYHZnyGURX5/p+UaisQUwEN+F90Nzijoqj1WVncK1OQ2O9z+AfoF3wO/3EHZaFIiwxjRLmEI6jteQ7zOrRaJ7vjkz5WKlmRWRYYhqlDgeHtJV859LH1iOWrDZFDUGGJaZRYsK9yszJdxje49Hs445M+Q9EV6yuLxYZlphG6YZFZk2+p7Bt1+1QCq+jU2RYYhp9MKzgynf8O0ZnKezKw01Rr/P9YtFTQjER3JA3o0lhxYGuOQg3/DG+Xwuf+/oO9LjBCTu4Rvu2eP38Wy1bOb/IPBbrwWKzsGphrtMcmiIsMRbckPdF0wezIiHJ95WQtVmRdw/NqnRkWGISfRgODmmUfIe58d5JYVPUX0Lvct3ykWGJSfTJsEiT5PvzINZeWXMcoqssN0UNQYYlJtE3w6qVfMf3bIhmwR2ZchP0HtftBzIsMYnSi0aXUrfynfMFOW/QmiMRXf3G93uBDEtMom8RFpmYfMfXaGoWT+CW8jPoQ67bH2RYYhJWhvV731owLfnOPBfXvLLmbYiust4UNQQZlhiJz+Vs6o6i8zXfWjEy+Y5rwlVEuZqoNT+F/tN1+4UMS4zDcjj4r761Ylzyneu0c712a+YRXVlGoWbIsMQ4rAxrHfQ56LLBkQ13Sb7DwFLZFPUC6BOu2z9kWGIcVoZ1GaIHLvH77+7QjKXJ9zdB3GvQmmI2RQ1BhiXGYWVYzM8Q5mi4IqgV65PvMC5OT+Iuztb8APpv1+0nMiwxDlPDQhTBuXGfYd+QYfL9IEiboiaADEvcBT8Uso6wiHWdEZPvu6D9Z3doytdgVl/2/d7SmWHhD/1taNFAN/qXIMLhk7B7uW50qobF8gbr5Pu/QfccHNnyVt/2mi4jrO/7NjZbwLS28X0RhlV0RdYbViLJ9xSWj/kirgXX3eo9XRoWE4RW7OXbaMAkt4eOh14C7Qrdw38pR6zmEK7Bjfkr3x9inXxvukZW29C0i9tyPpQSIyzyWN/GhBsRvBHiDXYe9GuY1gXQR6EDoL2hFIoO65BC/moADCyF5Lsln8I14PtJgM4MCxf5SjRWqyBGj7DA0rWR7gbtDL0I4tK7/wNdD9O6CToTOg56MfRoiLmSqeD7NoDu5w+7xMqwxuWrejfJ18NNUVOYaJ0MXUZYxCrK2g03NtcsigmfJtWBUz6eDrEQ8RToR9CteL3nQ6dCjMaeAW2B8wPQXwEdhe7V0ImDk91iZViX+3Yp1sl3Kz6KD/6LfV+Arg3LKo/FSaqMbmJS17BGwWiM/34/iNHYl6AbYVLrIK4myTftW6CtID5q3wxtJ+D/5ntiO3cUnZGmhJs2heR7bJi3S2GRwKQo1bBItGEhbnLmpoK2iZoCixWXrpjAR+wX4WeeAr0Z2tqdbo3l0EauG5275LAqWCffY3OST6uICjEMy6oyN2bifZboKgRGWlz18lhoS55oEcuShnFDwr4l37kp6jtcV1Tp1LDwJuMj6kmfml0SM/Ee27CGcBLsj123NawM6wa8X37t++PoS/L9/bgW1/u+qNB1hEWsEu87YLgUa/6X1e4pl+ONfZvvt0UyJQ0j6EPy/RboaNcVS4lhWFZ5LP5ue7hu51hFWFwbqW2SNSyYcx+S7yfg91zj+2IJJRsW6XxYiCiOFe0r3FF02o6uSMoRFik5+c5NUY93XTGKGIbFOqM7XDc6MRLvO0AsS7DgYb5tBZgva9e2dUfRqWVYiD5KTr4fjd+PQ0Ixhs4NC38AfhrStCyIkXi3Gg6SvWAybdZkcdK4lfk2eThTYvL9BihGUXDWxIiwiFXifcsO6pSW8mrfWsB6qRe4bitwlU0LmJsaW9IwghKT773bFDWEWIZlmcfqelhoVWQ55KW+bQOrVRquxc3K2qNa4HtLS75zylVf50s2ovQIi3Q9LGQRpyWPRxTZ1rbpqSfcq5SUfF/wqRMxhViGdQX0C9eNTmcRFoyiqyk5TWkryrIyrMbDO9zgpSTfL4VOdV0xjSiG5UP4s91RdHaHsWzg+21jmXCvwmVq2vgdc4qwSAnDqN5uihpCrAiLWA0L7w09ynVbJxXD4oOFp7luGDA8rsn1UHcUnVDDyj35fj50uuuKOsQ0rBILSK2m5Ixi1mEh66+6ikSnEWRYBSTfD8Xv0NtNUUOQYc1GKhEWmXWdLKvhIFfVXO26QeSafP8etMp1RV2iGRY+STg/isl3C1pPvMMcLKfkjILrZM1Sk2VlWFfjvRFsOPi3uSbf3+ojRNGAmBEWscpjPQoGw1xWm1hOyRnHLMPC3BLuVXJLvp8FszrL90UDYhuW1bCQuZndXbc1UhoODpmlJsuqaLQNw8ot+a5tuwLpS4RF2s5jpZRwrxIaZWUbYfmhVS7J98/j9X7X90VDYhsWJ0FbJUjbzmOlGGGRxjVZ+H7mv7qeczmOtiKjHJLvNNZDXVeEENWw8MnyWzRdLDpXh75EWCE1WZz0bLXDcZNJz2PBeyuH5Psn8TpZeyUCiR1hEath4XJEEq3svOz/nwe4oyRpOiy0Gg7+DrrKdVsh5eQ7q9m1KeqMWBhWCSs3pBpdDWlak2VlWKsRcbQ5LSXl5Pup+F05b1DMQJ8iLNKWYaWavxrStCYr55KG9cAQUk2+M7emTVFbwMKw+AnI3YwtaCuPlbphkSbDwiIMy5Ni8v1DMFOueSVmJLph+U9Bq5Ub9sBQqY3fOfUhIWlSk5VzDdadwPsrteQ7VxE90nXFrFhEWMRqWMh9ClmhHgxMgFNy2lowr2umRln4fe6D5kHuKDpdRFgkpeT7iTBRrtcuWsDKsHKeCL0jlNqUnHHUqcmyWseddGVYqSTfuQPOMa4r2qBvERaZ1bByyF8NqVOTZTUcZE3eNa7bLgkl39+N12K10m6RmBgW/og/R9Nm/U0TZn1SmJNhkWnDQquE+xV4H3S5FlQKyfdzfStawirCIlZR1s4YJm3s+yHkkHCvMq0mq6QnhOuBGVon3/nzGemJFrE0LKs8Fnc33s11g8gtwppWk2VlWDFyTFbJdw4Dt4FpaoG+lumjYZGgPBYildSn5Ixj0rDQyrBamUM4Bavk+2EwK22K2gGWhvVDyGq3kNDEe27DwSEja7Jw7r5oNndH0encSGAaFsn3K6GTXFe0jZlh+U+gC91RdEIT77kNB6uMirKsoivSaQ6rQuzkuzZF7RDLCItYJd63QXQRsgFqzoY1qibLyrBug6IUU8I82ki+132aeQn0UdcVXWBtWLmt3JDrkJCMqskye0Loh2uxCE2+c9h6AMSZAFxi+wxoEsxdcRcg0RF9NqxGeSxEJzlNyRnH0mGhmWH5NhZNku8czp0GPRVaAQM6jlEa9EPor3DuSdDXoaWcB33adUVXWBvWxRCnL1jQNMLKaUrOOJbWZPXCsGA0dZLvw2hqa3z/C6Gv+n93J3DuW9BT0N0bqk7i16aoETA1LP8HPscdRWdP3LxNlgXOOX81ZGlNVjGrNNRgVPJ9ZDTFL0wD33cmGn7oPQf6MI6/wPOiW6wjLGI1LGSk0eSGLcGwyGBYCLNmPdmm7BsQ3bC8EQ2T77WiqWnw30CfhV7hT4mOScGwclmBNOeEe5VhTZZVdEUsIixyFNQ4mhLp0HfDapJ4LyXCIoyyrPJX62AUnPweHfzcC6CgaEqkgblh4c3DepxOlhmpQa0ICxFJrlNyxvFiqE/5K1EIKURYxCrK2gVmtJHvT6KU4eAQ1mQ90XWjI8MSwaRiWFaJ97tDu7ruREoaDg7Zybex6XwOoSiXvhsWqTMsLNGwOPHZAkVYIphUDIsrM1pNaahjWKUNCS2RYYlgkjCsuWVrb0XzY3cUnYlPChfLmJKTEjIsEUwqERaxSrxvB1OatCZUCVNyUmENPpx+5ftCNCYlw0p1InSJ+SsrFF2JmZBhOWRYcZBhiZlIybCYw2Iuy4JJiXcl3NtDhiVmIhnDmnMLn1nt4zZp5QZFWO0hwxIzkVKERawS7/eHtnPd/6fAKTnWqGhUzERqhpVaAamGg+0SY2svUTBNFrDrHEQ0nONmNRH6vRiW7u/7A/B6DkRztDsSM3Ijri8j1iJYOb/I9dQoLgI4XGmUq0Dc4boDfgcNC6IXVy3MVb/WGXhth6OZd0dRWcDvyJ/dGUkZFoFJXIdmS3cUle/jhnqc7w/Aa+EOKC9yR2JGvoHr+2Tfz54WTKFqZuS3viXcr7O6Z2f1a++BKZzg+yMp2bBSGxISq2HhrjAoToauoiFheyjhfmdYjMyVQoYaRmwUC5m5U89Q21TEr/eWFA3LKvHOKTjrV26AeWlKTrvIsMTMpDgk5BK2X3FH0Xkthi0nsoPX8Rg03E5ftMNzcW0nbmhayQsR5oWGm0YszQ1Vh0h3YBgSfQVRvNYj0RzsjqJyCH7fd/j+SJTDigiMYhM0nG9mEf2dipvqJezgdXAZ4Y+wL1phF1zbC31/JC3nhap5IJ7j10jVCAnN7/240QYfVHXBa30nmoPcUVQOxmvlzx5LyYaV3JAQb2ruU8j9Ci2oljZYFYyug2533WJgBBSjpKGaF7o3NIzYWGc3zAfxgU41J7QCmjT5XSREijksYpV43x6R1XBhO6uE+/nQxKFThlyLD6LSTHgD38am15u1pmpYVol3DpGHE6GtIiwaFjf9LIm6CXc+6LBgOFxsgtWSQ0s3g+0VirDuyl6Isiyn5FwA8aGDVQFtF9Q1LKucarUeSiRMqobF5OxvXDc6jLAs66+4dx7D/lPcYRGUOIcwuQdWfSBJw8INy6c7ViUFTLxbDQf5SX+R6xY1LKybcLcaZoVEWFbD1yjTe1Il1QiLWOWxOBR8gutG53KY9SCyRMth1LfZL4C6EZZVIjskh2VFr3etTtmwLPNYu/k2NsxfVSkhymL0stp1hZgNRVij2cq3seETwiqfgHIvB7ga0WLdJ1tW78eQqGXpvNNY5BQNtk6yhoU3+dVobnJH0bG6LneKsHANWESbe01WkzmEViYQkheyeo/0+olmyhEWsRwWWrA0wiK5Dws16Vm0RuqGZTksjM1aaFTtVe41WaUalirdDVCElQ6sv7pLLgXncq/JamJYnANoQciQcEPfxkaV7glzNtSXx7ijhoNDch4W5hBh9bpUICeSNixEFxwmXeqOimdpScN6cB140+dYk8UnWle5bnGk/mFfJDlc9L7kscYalifHKOtKmG11bfJpWD0lbPIah+T0RLMYcjCsPuSxqlNyxpFjTVbTOYRW8/NCDMsKVbonTh8Ma/2UnHHg6znWZGkfQtEqORgWh0rVNbxLZNpwcEhuSzY3jbCsJj+HlArktHZXMSRvWIgs+Bj3PHdULJOeEFY5C/qZ62ZB0yeEVrVNIaUCWrvLgBwiLFJ64r1WhAXzZiRwqjvKglKLRoURuRhW6XmsuhEW4dPCHBKvHMY3rdC3irBCyGn4WgwyLHvGTckZCaKsXGqyrvARYROsTCAkR5rT8LUYcjEsrqe0xnWLY+SUnCnkUJOl4aBonSwMy9/QpUZZTYaDQz4JWa15X5cQw8ppnfRcPuyLIqeLXqph1S1pWA8MPIearBDDsioVCBlmWVW6l17iM5GcDKvUJ4WNDcuT+rAwpyFhrxPZOZFbhFXatIQ6U3LGkXpNlnJYonWyMSwMg36JprSpHlOn5IwD/y7lmqzboOtdtxFWQ8KQuYRWa3ep0j0jSstjhQ4Hh6Rak0UjDnldmvw8HVW6Z0RpeayQJ4TrgSlw2JViTVaJOz2LBFCEZcusERZJMfkemr/KqXo8p12qiyE3w/oRVFKl70wRlseiJutG6GRof+gg6CTo6xDzVhwKhhpWTtXjVq9VOaxcwBCIqy3StEqg0ZScceCaxKrJ4rU/HVoJLcfP/XvovdAx0Cuhp0DcgHYTiCYqROvkFmGRUvJYIVNyxtHlsJAbgbwG2hKv9/nQF6CxSWp87VYoNOLL6f2Y472TPTle9FLyWG0MB4e0XZPFId9x0E4wn72g90MsK+manKrHVelugAzLjjYS7gNgJm3UZHHI9yloH4hDvgOgH/MLQqRCjobFhG6MT/uuac2wPKE1WedAr4W2gkE9D1oF5VSXJHpEdoaFm4k3JfMqOTPLlJyR4Lo0qcm6CeKQb2f8uz2hE6FfDL5ii1X1eMhTQlW6G5Br4jD3xHvwlJwpTEq+86b8NLQvtDV+Pod8rZpmxuQ0+Vl1WBmSex6r7eHgkFE1WedCr4P4lO9voc9DGvKJLJFh2dDmE8L1wIiGNVkc8h0P7YJze0Dvg1IY8k3D6slbSNSiSncDsjQs3Hw3o+GyybnSiWF53gBxyPdm6EJ3Khus3o8heSFVuhuQa4RFco6yuhoS0szXQBryiSLJ2bByTbz/Cpp5Sk6hbOjb2ISUg+R872SLIqz4tDklpzSsDItFs01RpbsBORsWt6/PcTzf2XBQiNLJ1rAQpdyOJsebv8uEe+5omCUmkvsbJMdhoSKs8VgNs0KGhKp0NyB3w8ot8c4aGk0oTo9scoqrFuZUh5UxuUVYP8VQNvbqoEIUQ+6GdSm0znWzQMPByWQxzFo5v6gqdyOyNixEK5y0mtPKDTKsBAkYZqnK3YjcIyyS07BQTwiFmIESDCunxLsirDFgmJXTxGerCKv3KMKKh6bkTMbqvRgyzLLKYfW6yp1kb1hzy9Zyw4Sr3VHSaEqOEDNSQoRFcoiyNBycTE4Tn4URMqx4KOE+mZwmPue09nxRlGJYOSTeFWGJWclp7flOKMWwuG55yovW8UmUpuRMZs63QoylmDfJ4rLNuNzMru4oOS6ZW7Z2B983YeX84uFo5t1RVBZWLczxZ08Er+9BaG5wR1G5Ca+PP7s2eK3L0bS503ZdrsNr3dr3x5L633oWSomwSMrDQg0H0yUk6a5KdyNKMqyUE+8yLCFaQIYVBz0hnM49fBubkKhFle5GlGRYF0O/dt3kUIQ1Hat8asjUHFW6G1GMYc0tW8s33jnuKCk0JUeIligpwiIpDgs1JaceVlFL72ubcqI0w0rxSaGGg/WwyguFVI+r0t0IRVjdo4S7aAtVuvu2CDD0ug7Nte4oGRRh1UNP3sRUSouwSEpRlqbk1CenJ29a090IGVa3aJecMlGluxElGlZKiXcNB+ujyc9iKiUaFlduSCV0lmHVx6rSPeTJm/JtRhRnWBiCsdr9J+7IHD0hTJ+QJ2+qdDeixAiLpJLHUoQlRIuUalgp5LE0JacZVkPClBd+FEtQhNUdmpLTDKuke4hhqdLdiFINi7VPt7muGRoOirZRpbtviwKRDT81+bTQEiXcm6HJz2IqpUZYxHpYqAirGTlNfs5pW/2iKNmwLBPv/NTWlJxysbpvVOnu2xKxjLDWaUpOY1SMKaZSrGHBMLgNk9Uja+VFmpNTMaaVufb+qXOxhrW4bDM+erZ6Y22Kn2+V5xDdY2WuIdvqF0XJQ8IdIavaHv7cR7iuqIkmP4uplGxYP4dOct3o7IQh6UW+L+qR0+RnmasRJeewuPLom6DY+SROybnUdUUGhLw/cjLXoig5wqJp3YLmEncUDU3JEV2hpLtvS6ZJecOV0GnQgdAroFdDJ0BfhX4B1UEFo2FYPaTQ5OeM6INhjSsg5dDtS9AR0D7QAxEZbQu9EDoW+jD0QegN0FOhzfE9y6FnQQdDNDauu7W0+lhTcsKwei+GVI/LXI3oS4TFsf/Z0InQS6AV0P1hQs+EDoNWQTfj3ETwPddCX4TeCdHYHoXT94H2hBiRvQf6DiTKxuq+kWH5tmQY8WwCc9kLei10KnQp1Eo+AP/P7dA5ECOy10MX+y+JZmzo29ioyDcjijcsGMgfoN4X3GWAlWGFPHmzKkjuvbn2IcISom2sKt1V1uBbIazRe1FMRW8SkQpWT95CJj+r0t0IGZYQzbGqdNfkZ98KIdJHle6+FcIa7UQjpiLDEn0npFTAKt+mJZJ9K4SoDyfVXwVdD93oxeWM1lbEJbKZ0Kfayj31fhMKPe3oCSvnFw9HM++OorKwamGOP3sieH2HoVlwR1F5B17fIb4fBfyurOMaFp/yHqwm8atfI9Wh8lq8VprhRFL/W8+CDKsnZGBYr0ezvzsa3LDD4kyOAqpDsOoNzBt91vdw5zeZaA8ZVk8o+VOX4PejqQ1THNUoZZz5DSObNXh9awZnhBBCCCGEEEIIkSbLlv0fTWjyq2WT/7EAAAAASUVORK5CYII='
info_ico = b'iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADnMAAA5zATlgFakAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMTnU1rJkAAAC20lEQVRYR82ZvU4WQRSGPyQUVlBAib1eAEKCmGClFmon16CF0dLKSGEBiTbaqImVpZ2d3oGl3oDRisTKAjDo+2x2yXG+M7szO4P4Jk9Cduf87Ld75pxdJiM1K9bEQ/FOfBE/xK8W/uYY51jDWmxOXOfEE/Fd/M4EG2zxUV1L4rk4EF7wHPCBL3xW0ZbYE16wEvB5W4zWnHghPOcdX8UbcU/cEJdbbrbHOMcaz7aDGMTK0lnxXngOKYK3YkPMiCGxhrXYYOv5JBYxk8TVxJL7IM6LscIWH55vYib9kt5t5cG+L/p+sRXxqIW/Y8IHvryCI3avKIjQ6Ke4Jvq0LazNkXgs+oRPfFs7iBYOZR9WK1c5lNwlYW0s66JP+D4U1oYc3C2IvckuBG7FkHZFaNexI4ZEjNCOXP4Su3v4TPAwp1TpM2HtLE/FkIgRFs6+WBbHogXZBWwHqdV6VVhbC+dSdEGEWxA5NaKJh72VPStV/AKvhbWHVyJHxLT238QZ0Uwa9gSwseaIJG+Jly10kpTHw4qYYR7k1oxD9iCtKdd5DREzbIvk1sxs9iD987REbJsLuU0+mwNAkz8tEdvmQm7N9GsP8vzkaEF8EnQFC8fmRY6IbXMht6nyZlzK0aaw9hbO5YjY1p7cihO8Iqy9hXM5chMsvcU1E3RvcWmR1EzQLZLSbaZmgu42U7pR10owulGXtrpaCUZbXemwUCvB6LCASsatGgn2jluoZGAtTZAYH4W1mxpY0diRvzTBByK0mxr50diXppIEr4vklybEK59dDDT+viRXRWjTcVHERHL4Dm0Gv9d4L+5cZezFnWN3BS9Iljsitp7bGv5yMPjijoY+fVBxY4VtWBAdyZ8+0H/98agTV+Pdbgutif5Jk/+nn9+seGjD6q4BPos+YFpR9uxNbKBesBzwga9FUV3s7rQg+qQXvA9ssJ3qECchmjiTBuMQM1vKvyGOG3+6JpM/dn1f/WywEcoAAAAASUVORK5CYII='

fields_input = {
    'capital': 'Капитал',
    'balance_capital': 'Капитал',
    'payment': 'Регулярный платеж',
    'initial': 'Начальная сумма',
    'horizon': 'Инвест горизонт',
    'rate': 'Годовая доходность',
    'tax_enabled': 'Налоги',
    'inf_enabled': 'Инфляция',
    'stocks': 'Акции',
    'bonds': 'Облигации',
    'funds': 'Фонды',
    'metals': 'Драгметаллы',
    'pay_enabled': 'Докупить',
}

key_input_format_money = [
    'capital', 'payment', 'initial', 'balance_capital',
    'stocks', 'bonds', 'funds', 'metals', 'partial_repl'
]

key_input_format_percent = [
    'rate', 'percent_stocks', 'percent_bonds',
    'percent_funds', 'percent_metals', 'horizon'
]

key_input_format = key_input_format_money + key_input_format_percent

main_win_param = {
    'icon': main_ico,
    'grab_anywhere': True,
    'resizable': True,
    'finalize': True,
    'element_justification': 'c',
    # default_element_size: Any = None,
    # default_button_element_size: tuple[int, int] = (None, None),
    # auto_size_text: bool = None,
    # auto_size_buttons: bool = None,
    # location: tuple[int, int] = (None, None),
    # relative_location: tuple[int, int] = (None, None),
    # size: tuple[int, int] = (None, None),
    # element_padding: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | int = None,
    # margins: tuple[int, int] = (None, None),
    # button_color: tuple[str, str] | str = None,
    # font: Any = None,
    # progress_bar_color: tuple[str, str] = (None, None),
    # 'background_color': 'yellow',
    # border_depth: int = None,
    # auto_close: bool = False,
    # auto_close_duration: int = DEFAULT_AUTOCLOSE_TIME,
    # force_toplevel: bool = False,
    # alpha_channel: float = None,
    # 'return_keyboard_events': True,
    # use_default_focus: bool = True,
    # text_justification: Any = None,
    # 'no_titlebar': True,
    # grab_anywhere_using_control: bool = True,
    # keep_on_top: bool = None,
    # disable_close: bool = False,
    # disable_minimize: bool = False,
    # right_click_menu: list[list[list[str] | str]] = None,
    # transparent_color: str = None,
    # debugger_enabled: bool = True,
    # right_click_menu_background_color: str = None,
    # right_click_menu_text_color: str = None,
    # right_click_menu_disabled_text_color: str = None,
    # right_click_menu_selected_colors: tuple[str, str] | str | tuple = (None, None),
    # right_click_menu_font: Any = None,
    # right_click_menu_tearoff: bool = False,
    # ttk_theme: str = None,
    # use_ttk_buttons: bool = None,
    # modal: bool = False,
    # enable_close_attempted_event: bool = False,
    # 'titlebar_background_color': '#61FF5E',
    # titlebar_text_color: str | None = None,
    # titlebar_font: Any = None,
    # titlebar_icon: bytes | str = None,
    # use_custom_titlebar: bool = None,
    # scaling: float = None,
    # sbar_trough_color: str = None,
    # sbar_background_color: str = None,
    # sbar_arrow_color: str = None,
    # sbar_width: int = None,
    # sbar_arrow_width: int = None,
    # sbar_frame_color: str = None,
    # sbar_relief: str = None,
    # metadata: Any = None
}

cap_in = {
    'size': 15,
    # 'disabled': '',
    # 'password_char': ' ,
    'justification': 'c',
    'font': '_ 18',
    # 'tooltip': '',
    # 'border_width': '',
    'enable_events': True,
    # 'do_not_clear': '',
    # 'focus': '',
    'pad': (5, 10),
    # 'use_readonly_for_disable': '',
    # 'readonly': '',
    # 'expand_x': '',
    # 'expand_y': '',
    # 'right_click_menu': '',
    # 'visible': '',
}

other_in = {
    # 'disabled': '',
    # 'password_char': ' ,
    'justification': 'c',
    'font': '_ 12',
    # 'tooltip': '',
    # 'border_width': '',
    'enable_events': True,
    # 'do_not_clear': '',
    # 'focus': '',
    'pad': (5, 10),
    # 'use_readonly_for_disable': '',
    # 'readonly': '',
    # 'expand_x': '',
    # 'expand_y': '',
    # 'right_click_menu': '',
    # 'visible': '',
}

main_frame = {
    # 'title_location': '',
    # 'relief': '',
    # 'size': (150, 50),
    # 'font': '',
    # 'pad': '',
    # 'border_width': '',
    # 'tooltip': '',
    # 'right_click_menu': '',
    'expand_x': True,
    # 'expand_y': True,
    # 'grab': '',
    # 'visible': '',
    'element_justification': 'c',
    # 'vertical_alignment': 't',
}

main_btn = {
    # button_type: int = BUTTON_TYPE_READ_FORM,
    # target: str | tuple[int, int] = (None, None),
    # tooltip: str = None,
    # file_types: Any = FILE_TYPES_ALL_FILES,
    # initial_folder: str = None,
    # default_extension: str = '',
    # disabled: bool | str = False,
    # enable_events: bool = False,
    # image_filename: str = None,
    # image_data: bytes | str = None,
    # image_size: tuple[int, int] = (None, None),
    # image_subsample: int = None,
    # image_source: str | bytes = None,
    # border_width: int = None,
    # 'size': (10, 2),
    # auto_size_button: bool = None,

    # disabled_button_color: tuple[str, str] | str = None,
    # highlight_colors: tuple[str, str] = None,
    # mouseover_colors: tuple[str, str] | str = (None, None),
    # use_ttk_buttons: bool = None,
    # font: Any = None,
    'bind_return_key': True,
    # focus: bool = False,
    # 'pad': 15,
    # key: str | int | tuple | object = None,
    # right_click_menu: list[list[list[str] | str]] = None,
    'expand_x': True,
    'expand_y': True,
    # visible: bool = True,
}

lft_tabgroup = {
    'tab_location': 'topleft',
    # font: Any = None,
    'enable_events': True,
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[tuple[int, int], int] | int = None,
    # border_width: int = None,
    # 'tab_border_width': 1,
    # 'size': (50, None),
    # tooltip: str = None,
    # right_click_menu: list[list[list[str] | str]] = None,
    # expand_x: bool = False,
    # expand_y: bool = False,
    # visible: bool = True,
    # metadata: Any = None
}

rht_tabgroup = {
    'tab_location': 'topleft',
    # font: Any = None,
    # 'background_color': None,
    'enable_events': True,
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[tuple[int, int], int] | int = None,
    # border_width: int = None,
    # tab_border_width: int = None,
    # 'size': (500, 500),
    # tooltip: str = None,
    # right_click_menu: list[list[list[str] | str]] = None,
    # 'expand_x': True,
    # 'expand_y': True,
    # visible: bool = True,
    # metadata: Any = None
}

lft_col = {
    # 'background_color': 'red',
    # size: tuple[int | None, int | None] = (None, None),
    # size_subsample_width: float = 1,
    # size_subsample_height: float = 2,
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[tuple[int, int], int] | int = None,
    # scrollable: bool = False,
    # vertical_scroll_only: bool = False,
    # right_click_menu: list[list[list[str] | str]] = None,
    # visible: bool = True,
    # 'justification': 'c',
    # 'element_justification': 'center',
    'vertical_alignment': 'top',
    # grab: bool = None,
    # 'expand_x': False,
    # 'expand_y': True,
    # metadata: Any = None,
    # sbar_trough_color: str = None,
    # sbar_background_color: str = None,
    # sbar_arrow_color: str = None,
    # sbar_width: int = None,
    # sbar_arrow_width: int = None,
    # sbar_frame_color: str = None,
    # sbar_relief: str = None
}

rht_col = {
    # background_color: str = None,
    # size: tuple[int | None, int | None] = (None, None),
    # size_subsample_width: float = 1,
    # size_subsample_height: float = 2,
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[tuple[int, int], int] | int = None,
    # scrollable: bool = False,
    # vertical_scroll_only: bool = False,
    # right_click_menu: list[list[list[str] | str]] = None,
    # visible: bool = True,
    # 'justification': 'c',
    # 'element_justification': 'center',
    # 'vertical_alignment': 'top',
    # grab: bool = None,
    # 'expand_x': True,
    # 'expand_y': True,
    # metadata: Any = None,
    # sbar_trough_color: str = None,
    # sbar_background_color: str = None,
    # sbar_arrow_color: str = None,
    # sbar_width: int = None,
    # sbar_arrow_width: int = None,
    # sbar_frame_color: str = None,
    # sbar_relief: str = None
}

main_col = {
    'background_color': 'brown',
    # size: tuple[int | None, int | None] = (None, None),
    # size_subsample_width: float = 1,
    # size_subsample_height: float = 2,
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[tuple[int, int], int] | int = None,
    # scrollable: bool = False,
    # vertical_scroll_only: bool = False,
    # right_click_menu: list[list[list[str] | str]] = None,
    # visible: bool = True,
    # 'justification': 'c',
    # 'element_justification': 'center',
    # 'vertical_alignment': 'bottom',
    # grab: bool = None,
    'expand_x': True,
    'expand_y': True,
    # metadata: Any = None,
    # sbar_trough_color: str = None,
    # sbar_background_color: str = None,
    # sbar_arrow_color: str = None,
    # sbar_width: int = None,
    # sbar_arrow_width: int = None,
    # sbar_frame_color: str = None,
    # sbar_relief: str = None
}

chbx = {
    # default: bool = False,
    # size: tuple[int, int] | tuple[None, None] | int = (None, None),
    # auto_size_text: bool = None,
    # font: Any = None,
    # background_color: str = None,
    # text_color: str = None,
    # checkbox_color: str = None,
    # 'enable_events': True,
    # disabled: bool = False,
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[tuple[int, int], int] | int = None,
    # tooltip: str = None,
    # right_click_menu: list[list[list[str] | str]] = None,
    # expand_x: bool = False,
    # expand_y: bool = False,
    # visible: bool = True,
}

combo_per = {
    # size: tuple[int, int] | tuple[None, None] | int = (None, None),
    'auto_size_text': True,
    # background_color: str = None,
    # text_color: str = None,
    # button_background_color: str = None,
    # button_arrow_color: str = None,
    # bind_return_key: bool = False,
    # enable_events: bool = False,
    # disabled: bool = False,
    'pad': (5, 10),
    # expand_x: bool = False,
    # expand_y: bool = False,
    # tooltip: str = None,
    'readonly': True,
    'font': '_ 11',
    # visible: bool = True,
}

expl_t = {
    # text: Any = '',
    # size: Any = (None, None),
    # auto_size_text: bool = None,
    # click_submits: bool = False,
    # enable_events: bool = False,
    # relief: Any = None,
    # font: Any = None,
    # text_color: str = None,
    'background_color': 'red',
    # border_width: int = None,
    # justification: str = None,
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[
    # tuple[int, int], int] | int = None,
    # p: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[
    # tuple[int, int], int] | int = None,
    # key: str | int | tuple | object = None,
    # k: str | int | tuple | object = None,
    # right_click_menu: list[list[list[str] | str]] = None,
    # 'expand_x': True,
    # 'expand_y': True,
    # grab: bool = None,
    # tooltip: str = None,
    # visible: bool = True,
    # metadata: Any = Non
}

rht_tab = {
    # title_color: str = None,
    # background_color: str = None,
    # font: Any = None,
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[
    # disabled: bool = False,
    # border_width: int = None,
    # tooltip: str = None,
    # right_click_menu: list[list[list[str] | str]] = None,
    # 'expand_x': True,
    # 'expand_y': True,
    # visible: bool = True,
    # element_justification: str = 'left',
    # image_source: str | bytes | None = None,
    # image_subsample: int = None,
}

cvs = {
    # background_color: str = None,
    # size: tuple[int, int] | tuple[None, None] = (None, None),
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[tuple[int, int], int] | int = None,
    # tooltip: str = None,
    # right_click_menu: list[list[list[str] | str]] = None,
    # 'expand_x': True,
    # 'expand_y': True,
    # visible: bool = True,
    # border_width: int = 0,
}

exp_both = {
    'expand_x': True,
    'expand_y': True,
}

col_popup_error = {
    'justification': 'c',
    'element_justification': 'l',
    'vertical_alignment': 'c',
}

popup_errors = {
    'font': 'Courier 12',
    # return_keyboard_events: bool = False,
    'text_justification': 'c',
    # no_titlebar: bool = False,
    # grab_anywhere: bool = False,
    # grab_anywhere_using_control: bool = True,
    'keep_on_top': True,
    'finalize': True,
    'element_justification': 'c',
    'modal': True,
}

table = {
    'headings': ['Год', "Начало года", "Пополнение за год", "Доход за год", 'Налог за год', "Конец года"],
    # 'visible_column_map': [True, True, True, True, True],
    'col_widths': [5, 15, 15, 15, 15, 15],
    # def_col_width: int = 10,
    'auto_size_columns': True,
    # max_col_width: int = 20,
    # select_mode: enum.pyi = None,
    # display_row_numbers: bool = False,
    # num_rows: int = None,
    'row_height': 50,
    'font': 'Courier 14',
    'justification': 'c',
    # text_color: str = None,
    # background_color: str = None,
    # alternating_row_color: str = None,
    # selected_row_colors: str | tuple[str, str] = (None, None),
    # header_text_color: str = None,
    # header_background_color: str = None,
    'header_font': 'Courier 10',
    # header_border_width: int | None = None,
    'header_relief': sg.RELIEF_FLAT,
    # row_colors: list[tuple[int, str] | tuple[Any, str, str]] = None,
    'vertical_scroll_only': True,
    'hide_vertical_scroll': True,
    # border_width: int = None,
    # sbar_trough_color: str = None,
    # sbar_background_color: str = None,
    # sbar_arrow_color: str = None,
    # sbar_width: int = None,
    # sbar_arrow_width: int = None,
    # sbar_frame_color: str = None,
    # sbar_relief: str = None,
    # size: tuple[int, int] = (None, None),
    # enable_events: bool = False,
    # enable_click_events: bool = False,
    # right_click_selects: bool = False,
    'bind_return_key': True,
    # pad: tuple[int, int] | tuple[tuple[int, int], tuple[int, int]] | tuple[int, tuple[int, int]] | tuple[
    # tooltip: str = None,
    # right_click_menu: list[list[list[str] | str]] = None,
    'expand_x': True,
    'expand_y': True,
    # visible: bool = True,
}
